version: '3.0'

services:
  db:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    volumes:
      - "./migrations/data.sql:/docker-entrypoint-initdb.d/data.sql"
  app:
    #image: "juanmesaglio/tp:latest"
    build:
      dockerfile: "Dockerfile"
      context: .
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "8080:8080"
  front:
    build: 
      context: "vulnerable-app-ui/"
      dockerfile: "Dockerfile"
    depends_on:
      - app
    links:
      - "app:app"
    ports:
      - "3000:3000"
      